### ISSUE TITLE
HTTP Errors do not seem to be tracked

### ISSUE THREAD

**Issue by Lawouach** [rycus86/prometheus_flask_exporter#1]
Hi there,

I noticed that, non-global metrics do not seem to handle HTTP errors raised by flask. For instance, for this very dummy handler:

```

@app.route('/')
@metrics.summary('http_index_requests_by_status',
                 'Request latencies by status',
                 labels={'status': lambda r: r.status_code})
@metrics.histogram('http_index_requests_by_status_and_path', 
                   'Index requests latencies by status and path',
                   labels={
                       'status': lambda r: r.status_code,
                       'path': lambda: request.path})
def index():
    if not state["running"]:
        return abort(500)
    return 'Hello World!'
```

The `http_index_requests_by_status_and_path` metric never reports the 500 whereas the global `flask_http_request_duration_seconds_count` does. I wonder if the code handles the exception that is triggered by calling ̀abort(500)`.

**Comment by rycus86** [comment]
Hi @Lawouach ,

Thanks a lot for letting me know and for providing a failing example!
It was super helpful and hopefully https://github.com/rycus86/prometheus_flask_exporter/commit/9e3c9a64250b8f8c3d900b48970c21107048fe47 fixes the issue.
Please try again with version 0.1.2 and let me know if it doesn't work.

Thanks!

**Comment by Lawouach** [comment]
Hi @rycus86.

Thanks for the swift fix. I will definitely do next week.

Really useful project by the way!
Thanks,
