### ISSUE TITLE
Support using a prefix other than "flask"

### ISSUE THREAD

**Issue by jeteon** [rycus86/prometheus_flask_exporter#10]
I've noticed that all the metrics have the prefix "flask" hardcoded for them. In my environment, I'd like to use the library on multiple Flask based applications. It would be nice to be able to assign each one a unique prefix. Is this something that would be welcome as an addition to the library or is the official way to deal with this metric relabelling on ingest?

**Comment by rycus86** [comment]
Hi @jeteon ,

Sounds like a totally valid use case. I can have a look at it, should be a fairly trivial change I think.
Alternatively, I'd review a PR for it. 🙂

Thanks for the suggestion!

**Comment by rycus86** [comment]
Hi @jeteon ,

The `defaults_prefix` should do what you want now.
Thanks again!

**Comment by jeteon** [comment]
You beat me to it 😄. Thanks again for making this library available.
