### ISSUE TITLE
Alert manger for custom exception from the service

### ISSUE THREAD

**Issue by jishnu-das-t** [rycus86/prometheus_flask_exporter#103]
I would like to alert Prometheus for custom exceptions from the application. I can right rules for basic Memory/Cpu/HTTP errors but not for some custom exception in the application. Is there a way to raise an alert for custom exceptions to Prometheus and then to Alert manager? Any help would be appreciated. Thanks.

**Comment by rycus86** [comment]
I haven't played much with AlertManager, but what do the docs say about options here? Is it not as easy as having a counter on number of errors and configuring it to fire off an alert when the increase is too large in a short time window?

**Comment by jishnu-das-t** [comment]
Thanks for your reply. The documentation doesn't mention any option for sending an alert for custom exceptions from the application. I can create rules for some predefined criteria related to memory/CPU/HTTP requests. But they haven't mentioned any configuration to fire off an alert from the application to prometheus and then to the alert manager. If you can help me with any reference/guidance to fire off an alert to prometheus from custom exceptions, that would be really helpful.

**Comment by rycus86** [comment]
I'd probably start at https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
It sounds like the `expr` of a rule can be used to configure whatever expression you'd like, so a custom counter's increase per 5 minutes being over a low threshold for example should be doable.

Does this help?

**Comment by jishnu-das-t** [comment]
Thanks for your help. closing the issue as resolved.
