### ISSUE TITLE
Running with https 

### ISSUE THREAD

**Issue by jishnu-das-t** [rycus86/prometheus_flask_exporter#104]
I would like to run prometheus in domain "https://example.com". I'm not able to find any supporting documentation for hosting prometheus with https encryption.If you have any reference/guide to help me out with this, Please share it . Thanks.

**Comment by rycus86** [comment]
Hi @jishnu-das-t 

There are several options you could try:
- it looks like you can run Prometheus with TLS enabled https://prometheus.io/docs/prometheus/latest/configuration/https/
- you can also put it behind a webserver, like nginx, that would do the actual HTTPS termination https://prometheus.io/docs/guides/tls-encryption/ (I'd recommend this)
- something more Cloud native like Traefik can automatically get a Let's Encrypt certificate for you and discover Prometheus if you run both in Docker or Kubernetes https://github.com/traefik/traefik

Does this help?

**Comment by jishnu-das-t** [comment]
Hi @rycus86  I have tried the same way as you suggested, but no luck. I'm getting 502 Bad Gateway error on " https://mydomain.com/prometheus/metrics ".
I was running my flask app behind nginx and below was my configurations. Please help me to get out of this ...
prometheus.yml

![promethues](https://user-images.githubusercontent.com/65754205/119169646-e45f5d00-ba7f-11eb-85cf-8e727e1a336c.png)

docker-compose.yml

![docker-compose-1](https://user-images.githubusercontent.com/65754205/119169718-f9d48700-ba7f-11eb-9ae0-73a0cf8a3c77.png)

nginx.conf
![nginx_conf](https://user-images.githubusercontent.com/65754205/119169990-45873080-ba80-11eb-8516-2b4c7ed19a43.png)

**Comment by rycus86** [comment]
The https://prometheus.io/docs/guides/tls-encryption/#prometheus-configuration documentation calls out some Prometheus command line parameters to pass in when you run it behind Nginx, e.g. `--web.external-url` and `--web.route-prefix`, I see that you're not setting these in your composefile. 

Additionally the Nginx 502 might mean some nginx misconfiguration, check `nginx -t` inside the Nginx container to see if it reports any configuration problems.

**Comment by jishnu-das-t** [comment]
Closing as the configuration got worked. Thanks @rycus86
