### ISSUE TITLE
flask_http_request_total url_path missing label

### ISSUE THREAD

**Issue by EvertonSA** [rycus86/prometheus_flask_exporter#105]
Is it only here or flask_http_request_total does not gather url path labels? How can I enable it?
![image](https://user-images.githubusercontent.com/30481051/120091089-14d97380-c0de-11eb-8df5-bb1aab18168b.png)

**Comment by EvertonSA** [comment]
tried to use flask_http_request_duration_seconds_sum or flask_http_request_duration_seconds_count but it seems its adding latencies instead of counter. mabye i'm missing something here

**Comment by rycus86** [comment]
Hm, that's odd. Can you check what's the output you're getting on the /metrics endpoint in your Flask app?

**Comment by EvertonSA** [comment]
wil do it in te morning!

**Comment by rycus86** [comment]
Oh, just checked https://github.com/rycus86/prometheus_flask_exporter#default-metrics and it looks like the total is supposed to be by method and status only.

The `flask_http_request_duration_seconds` is a histogram, so the `le=+Inf` with the `path` label should give you the total number of requests by path. Is that what you're after?

**Comment by EvertonSA** [comment]
sorry cant provide more details, havent look at this for ages. thanks for the help I appreciate
