### ISSUE TITLE
Exceptions (Status code 500) are counted twice

### ISSUE THREAD

**Issue by idlefella** [rycus86/prometheus_flask_exporter#113]
Hi

I installed the prometheus_flask_exporter with the latest version of flask (v2.0.2) and realized that when the endpoint raises and exception, that the counter for the 500 status code is counted twice.

The issue seems to be that both callbacks `after_request` and `teardown_request` increment the counter +1. For other status codes, the code works as expected because the first if statement in the `teardown_request` function filters for exceptions only:

https://github.com/rycus86/prometheus_flask_exporter/blob/master/prometheus_flask_exporter/__init__.py#L455-L457

I can provide a fix, the question is only what the proper solution is. According to the docs, `teardown_request` is triggered after every request. Would it make sense to remove the `after_request` callback?

Best,
idlefella

**Comment by rycus86** [comment]
Thanks a lot for reporting this issue, and so awesome to put here steps to reproduce it!
Is this perhaps a change in Flask 2? I wonder why this wasn't an issue before.
I think there's some code already between the handlers that tries to avoid double-counting, perhaps that needs to be adjusted.

If you have ideas for the fix, I'm happy to review a PR.
Otherwise I'll try to have a look this weekend and test + fix it with the latest Flask.

Thanks again!

**Comment by rycus86** [comment]
Thanks again for reporting this! I've now merged in a fix for this in https://github.com/rycus86/prometheus_flask_exporter/commit/c9ff2b11b776156760c05c94e891b08d960eb62e

I had a brief look at your suggested fix, but removing either `after_request` or `teardown_request` breaks a lot of unit tests, so I decided to flag the request with an attribute to avoid double-counting. I also noticed that the unit tests don't have this problem, so perhaps there's a slight difference how Flask behaves in `testing` mode.

With `GunicornInternalPrometheusMetrics` I could reproduce the issue even just running the app with `app.run` so it's probably not a multiprocessing issue, but strange that no one has noticed this issue so far.

Thanks again! The fix should now be available in version `0.18.6`

**Comment by idlefella** [comment]
Hi @rycus86 

I also wanted to add a unittest for that case, but realized that when an exception is thrown in the application, the unittest also fails immediately due to that exception. I then stopped working on it because I didn't have enough time besides work.

But thank you so much for providing a fix in such a short time!
