### ISSUE TITLE
The formatting in pypi is broken

### ISSUE THREAD

**Issue by geekodour** [rycus86/prometheus_flask_exporter#12]
https://pypi.org/project/prometheus-flask-exporter/

What can be done to fix this?

**Comment by rycus86** [comment]
Thanks for reporting this!
When I looked at it a long time ago, I thought the only option is to add a *reStructuredText* version of the README and maintain that separately, which I didn't want to do.
Now, it looks like PyPI should support Markdown, just needs some metadata in `setup.py`: https://packaging.python.org/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata
I'll have a look if this does work.
Thanks again!

**Comment by rycus86** [comment]
OK, it looks better now: https://pypi.org/project/prometheus-flask-exporter/0.3.3/
Thanks for making me look into this! :)
