### ISSUE TITLE
start_http_server run uwsgi in production mode

### ISSUE THREAD

**Issue by rhuanbarreto** [rycus86/prometheus_flask_exporter#122]
I'm using `metrics.start_http_server` in order to have a separate server on a different port. But the server starts in development mode and all the access logs goes to `stderr`. How can I run this in production mode?

**Comment by rycus86** [comment]
That function delegates to https://github.com/prometheus/client_python/blob/4e0e7ff7e615601a35376c414b7081945ed417f8/prometheus_client/exposition.py#L165 so whatever configuration that underlying wsgi server has we should support.
