### ISSUE TITLE
Multiprocess applications metrics running in werkzeug 

### ISSUE THREAD

**Issue by Velan987** [rycus86/prometheus_flask_exporter#123]
For a multiprocess applications only the metrics which has "flask_" prefix is exposed.
Common metrics like "process_resident_memory_bytes, process_cpu_seconds_total" are not exposed, for single process application these metrics are available.

I am running the application like below
app.run(host='0.0.0.0', port=8080, processes=10, threaded=False)

**Comment by rycus86** [comment]
We've run into this before, and there's an easy-to-miss paragraph about it in the README ( under https://github.com/rycus86/prometheus_flask_exporter#multiprocess-applications )

>  Please also note, that the Prometheus client library does not collect process level metrics, like memory, CPU and Python GC stats when multiprocessing is enabled. See the https://github.com/rycus86/prometheus_flask_exporter/issues/18 issue for some more context and details.
