### ISSUE TITLE
Jinja2 Update 3.1.0 breaks Multiprocess

### ISSUE THREAD

**Issue by rokpu** [rycus86/prometheus_flask_exporter#124]
The latest release from Jinja2 breaks the multiprocess because the package version for Jinja isn't set. See release notes - https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0

This can be remediated by either hard setting the Jinja2 package to 3.0.3 or import escape directly from `MarkupSafe`

**Comment by rycus86** [comment]
Thanks for reporting this! Do you have an error message on how this manifests? Is it a pip error or a runtime issue?

**Comment by rokpu** [comment]
No problem, I encountered it yesterday for the first time. It's a runtime error.
<img width="1243" alt="Screen Shot 2022-03-25 at 6 06 46 PM" src="https://user-images.githubusercontent.com/18668171/160208696-12b957ca-93b6-4b54-a8ce-4f9a7e99bc89.png">

**Comment by rycus86** [comment]
I just tried running the test in https://github.com/rycus86/prometheus_flask_exporter/blob/master/examples/uwsgi/Dockerfile locally, and that seems to work as expected, while resolving Jinja2 to version 3.1.1 (based on the logs).
What's your `requirements.txt` looking like? Are you perhaps pinning some of the packages but not others?

**Comment by rokpu** [comment]
That's interesting. All packages are pinned in my requirements file.
See below
`
ansicolors==1.1.8
colorlog==4.2.1
flask==1.1.2
flask-cors==3.0.8
flask-seasurf==0.3.0
flask-talisman==0.7.0
icontract==2.3.4
itsdangerous==2.0.1
marshmallow==3.6.1
Jinja2==3.0.3
prometheus-flask-exporter==0.19.0
PyGithub==1.55.0
pynamodb==4.3.2
python-gitlab==2.4.0
pytz==2020.4
requests==2.23.0
webargs==6.1.0
`

**Comment by rokpu** [comment]
Upgrading most of the packages within the app seems to have fixed the above issue.
Not entirely sure what package was holding it back.

**Comment by rycus86** [comment]
Sounds like you've worked it out, so I'll go ahead and close this issue. If you're pinning all packages, then I'd expect explicitly adding the markupsafe package along with the jinja2 bump would probably also work.

**Comment by rokpu** [comment]
Agreed, thanks for the help.
