### ISSUE TITLE
ImportError: cannot import name 'choose_encoder' from 'prometheus_client.exposition' 

### ISSUE THREAD

**Issue by danielbraun89** [rycus86/prometheus_flask_exporter#128]
Newest prometheus_client 0.14 breaks compatibility (choose_encoder was removed)

**Comment by rycus86** [comment]
I expect this should be fixed by https://github.com/rycus86/prometheus_flask_exporter/pull/126 in `prometheus_flask_exporter` version `0.20.0` - are you perhaps pinning some packages but not others?

**Comment by kojiromike** [comment]
I can confirm this _was_ broken with the combination of 

```
prometheus-flask-exporter<0.20.0
prometheus-client>=0.14.0
```

and works fine with either

```
prometheus-flask-exporter>=0.20.0
prometheus-client>=0.14.0
```

or

```
prometheus-flask-exporter<0.20.0
prometheus-client<0.14.0
```

so basically users can either _pin_ carefully, or unpin and just make sure they aren't getting a bad combination.

**Comment by rycus86** [comment]
We could potentially release a new version that tries importing `choose_formatter` and if that didn't work fall back to importing `choose_encoder`. I'd be happy to review a PR for that, or I can try have a look myself later.

**Comment by rycus86** [comment]
Thanks to @kojiromike adding a change in https://github.com/rycus86/prometheus_flask_exporter/pull/129 the `0.20.1` version should now work with the latest and also with the older version of `prometheus_client`, so pinning either of them or both should all work. (for example if Renovate is bumping your packages one by one).

**Comment by Starkteetje** [comment]
Except if you pin only an old version of the exporter, i.e. `prometheus-flask-exporter~=0.19.0` but not the client. In that case you get the incompatible versions 0.19.0 and 0.14.0

Would pinning the client version be an option for you?
