### ISSUE TITLE
Add support for grouping by url_rule

### ISSUE THREAD

**Issue by nonnib** [rycus86/prometheus_flask_exporter#13]
In PR#3 the following flag was added: `group_by_endpoint`. This is a great addition since it allows you to group metrics by route rather then by absolute path.

However, this will log out metrics grouped on the route name, e.g. `api.users_user` whereas it might be better to group it on the rule, e.g. `/users/<int:user_id>` (`request.url_rule`)

Maybe `group_by_endpoint` can be extended to support either `url_rule` specifically or maybe make this more general by exposing `duration_group` directly?

**Comment by rycus86** [comment]
Hm... Just looking at the Prometheus docs at: 

> Label names may contain ASCII letters, numbers, as well as underscores. They must match the regex [a-zA-Z_][a-zA-Z0-9_]*. Label names beginning with __ are reserved for internal use.

Sounds like we can't use the rule as-is. Maybe we need something like a `label_name_generator` or similar?

**Comment by nonnib** [comment]
Ah, didn't realize that. Probably not worth the effort then.
The `.` in the `endpoint`, e.g. `api.users_user` might not be supported either?

**Comment by rycus86** [comment]
Hm, good spot! I'll have a look, might need to sanitize it (though that would be a breaking change).

**Comment by rycus86** [comment]
Oh... I should have read the line exactly below the one I copied here. It says:

> Label values may contain any Unicode characters.

So it's all good. I'll have a look how to best add the `rule` rather than the `endpoint`.
