### ISSUE TITLE
After MultiProcessCollector used, the exposed endpoint `/metrics` has no value returned

### ISSUE THREAD

**Issue by YaoJusheng** [rycus86/prometheus_flask_exporter#131]
I'm using `MultiProcessCollector` with `UWsgiPrometheusMetrics`, why does the endpoint  `/metrics` return none?

I have tried some of the cases in the [examples](https://github.com/rycus86/prometheus_flask_exporter/tree/master/examples) and found that none of them worked.

**Comment by rycus86** [comment]
Do you have a specific example you tried? Or maybe a minimal app you could share? GitHub actions ran a bunch of the examples you linked successfully not so long ago: https://github.com/rycus86/prometheus_flask_exporter/actions/runs/2111681953

**Comment by rycus86** [comment]
Got it, thanks. I'll try to have a look this weekend to see what might be going on.

**Comment by rycus86** [comment]
OK, I double checked the uwsgi example in the repo, and I can confirm it still works as expected.
Note, that in the example we start uwsgi on port 4000, see https://github.com/rycus86/prometheus_flask_exporter/blob/master/examples/uwsgi/Dockerfile#L18 
But the metrics endpoint will be exposed on a dedicated port ( see https://github.com/rycus86/prometheus_flask_exporter/blob/master/examples/uwsgi/server.py#L9 ) which is configured to be 9200 for our example ( see https://github.com/rycus86/prometheus_flask_exporter/blob/master/examples/uwsgi/Dockerfile#L16 )

So from your example above you start the *main app* on port 9000
> uwsgi --http 0.0.0.0:9000 --module xxx:app --master --processes 2 --threads 2

But you should also start a new server to expose the metrics endpoint with `metrics.start_http_server(<metrics-port>)` and try `curl` on that port.

**Comment by YaoJusheng** [comment]
In my example, when I try UWsgiPrometheusMetrics, I am using port 8200 to get the metrics, but no matter how I request the `/test` interface, the metrics endpoint returns no change in value.

**Comment by YaoJusheng** [comment]
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/42117749/167234547-f140f7d4-e6ee-44dd-866f-749e8b04acf1.png">

<img width="890" alt="image" src="https://user-images.githubusercontent.com/42117749/167234531-4df4e992-8ed3-4383-929c-b38e11d52864.png">

**Comment by rycus86** [comment]
Tried the example again and I see that the metrics change when I hit the test endpoint - though note that I checked on the latest version, which is `0.20.1` but I can't remember fixing anything related to uwsgi issues.

I think as a next step, it would be helpful if you could put your example app (requirements, scripts and everything else) in a GitHub repo, so I could reproduce exactly what you're doing.

**Comment by YaoJusheng** [comment]
> Tried the example again and I see that the metrics change when I hit the test endpoint - though note that I checked on the latest version, which is `0.20.1` but I can't remember fixing anything related to uwsgi issues.
> 
> I think as a next step, it would be helpful if you could put your example app (requirements, scripts and everything else) in a GitHub repo, so I could reproduce exactly what you're doing.

Here is my uwsgi example, in the meantime I have just upgraded to version 0.20.1:
```python
import os

from flask import Flask
from prometheus_flask_exporter.multiprocess import UWsgiPrometheusMetrics

tmp_dir = os.path.join(os.path.dirname(__file__), 'tmp')
os.environ['PROMETHEUS_MULTIPROC_DIR'] = tmp_dir
if not os.path.exists(tmp_dir): os.mkdir(tmp_dir)

app = Flask(__name__)

metrics = UWsgiPrometheusMetrics(app)


@app.route('/test')
def index():
    return 'Hello world'


metrics.register_endpoint('/metrics', app)
metrics.start_http_server(8200)

if __name__ == '__main__':
    app.run(debug=False, port=5000)

```

**Comment by YaoJusheng** [comment]
I think it may be due to the `MultiProcessCollector`, I found no files in the `tmp` directory.

As shown in the example above, in addition to this, do I need to add some configuration to work with `MultiProcessCollector`?

**Comment by rycus86** [comment]
Now that you mention it, try setting the environment variable before you start the Python (or uwsgi) process instead of setting it within the app from the Python code, if I remember correctly that didn't always work.

**Comment by YaoJusheng** [comment]
Thanks a lot!

The problem is solved, the developer does  need to set the environment variables directly before the program starts, the settings in the code don't take effect.

By the way, can uwsgi be mixed and matched with restful?

**Comment by rycus86** [comment]
Awesome, glad you found the issue! Perhaps I should document it in the README, though it's probably more a property of the underlying prometheus_client library than this one.

> By the way, can uwsgi be mixed and matched with restful?

There are some examples mixing uwsgi with other frameworks in the repo, so I think it should be doable but didn't try it. Feel free to open a new issue if you try it and find it that it doesn't work.
