### ISSUE TITLE
AttributeError: 'Request' object has no attribute 'prom_start_time'

### ISSUE THREAD

**Issue by nonnib** [rycus86/prometheus_flask_exporter#14]
`before_request` from `export_defaults()` is not guaranteed to run if some other `before_request` hook raises exception, for example for authentication.

Therefore, when `after_request` is triggered `request.prom_start_time` might not be set. 

Suggested fix would be to skip the histogram section in `after_request` if `request` has no `prom_start_time` attribute.

**Comment by rycus86** [comment]
Thanks for the report!
Would you have a small example to test?
When I try raising an exception, the `after_request` hooks is not triggered either - though unit tests might behave differently.

Thank you!

**Comment by nonnib** [comment]
Yes, I'm sorry, I should have elaborated. an unhandled exception will of course just crash in the before_request hook, but if the exception is handled by the app (or flask) `before_request` handlers which are unlucky enough to be processed after that one won't get called, but `after_request` handlers will be called as usual.

Minimal example here:
```python
from flask import Flask
from werkzeug.serving import run_simple
from prometheus_flask_exporter import PrometheusMetrics
from werkzeug.exceptions import HTTPException
app = Flask(__name__)

@app.before_request
def before_request():
    raise HTTPException(404) # or abort(404)

# if we initialize the metrics middleware _after_ our own before_request handler
# we ensure (as much as dict ordering can be ensured) that its `before_request` handlers
# are called after the one above.
metrics = PrometheusMetrics(app)

if __name__ == '__main__':
    run_simple('localhost', 8080, app, use_reloader=False)
```

navigate to http://localhost:8080 and you should get this error:
```
Traceback (most recent call last):
...
  File "/venv/lib/python3.6/site-packages/prometheus_flask_exporter/__init__.py", line 239, in after_request
    total_time = max(default_timer() - request.prom_start_time, 0)
  File "/venv/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'prom_start_time'
```

**Comment by rycus86** [comment]
That's perfect, thank you very much!
I'll have a look at it soon.

**Comment by rycus86** [comment]
Version `0.3.4` will have this in about 10-15 minutes.

**Comment by nonnib** [comment]
That's an amazing turn-around time, thank you!
