### ISSUE TITLE
prometheus_flask_exporter/examples/uwsgi-lazy-apps/server.py

### ISSUE THREAD

**Issue by wuhaotju** [rycus86/prometheus_flask_exporter#152]
hello, in this python file, start_http_server(9100)
why can't i curl 127.0.0.1:9100/metrics?

**Comment by rycus86** [comment]
Hi,
Hm yeah that does look misleading.
It looks like the actual port is 5000 if you run the Python file directly, or 4000 if you run it through Docker as the integration tests do it, and the metrics endpoint is bound to the app there.
I think the start_http_server may be a copy-paste leftover in that file. 😅

**Comment by wuhaotju** [comment]
hi,
in this code, i add the follow code
`
from flask_cors import CORS
CORS(app)
`
i got an error, how can i fix it? 
thanks

**Comment by rycus86** [comment]
I'm not too sure, can you explain a bit more what are you trying to achieve? If you have a (preferably minimal) example as a snippet or in a repo, that might be useful as well.

**Comment by wuhaotju** [comment]
`from flask import Flask
from flask_cors import CORS
from prometheus_flask_exporter.multiprocess import UWsgiPrometheusMetrics

app = Flask(__name__)
metrics = UWsgiPrometheusMetrics(app)
metrics.register_endpoint('/metrics')

CORS(app)

@app.route('/test')
def index():
    return 'Hello world'


if __name__ == '__main__':
    metrics.start_http_server(9100)
    app.run(debug=False, port=5000)`
the code is up there,
i need to add CORS() in the code, but i got the error.

**Comment by rycus86** [comment]
I just tried it using the same example, and using `from flask_cors import CORS`, just need to make sure you have the package available (`flask-cors` in the requirements.txt).
If it doesn't work, can you please explain the error message you're getting from the app?

**Comment by wuhaotju** [comment]
ohhh, i know, i put the `CORS(app)` up `metrics = UWsgiPrometheusMetrics(app)` . it's works.
but i want to start new port like 9100 not the 4000 or 5000, seems `metrics.start_http_server(9100)` not work.
if there is other solutions?

**Comment by rycus86** [comment]
That is mentioned in the README as not working, see https://github.com/rycus86/prometheus_flask_exporter#uwsgi-lazy-apps
