### ISSUE TITLE
Restrict access to /metrics endpoint

### ISSUE THREAD

**Issue by fritjofbuettner** [rycus86/prometheus_flask_exporter#16]
Hi,
for security reasons, I would like to restrict access to the `/metrics` endpoint to a certain IP address (the external Prometheus server).
What would be the best way to implement this?
Thanks!

----

*Python 3.6, Flask 1.0.2, prometheus-flask-exporter 0.5.1*

**Comment by rycus86** [comment]
Hi,

I would probably do something like this in a reverse proxy in front of the Flask application.
If you do want to do it with this library though, then you'll probably have to disable the automatic `/metrics` endpoint registration and do it yourself, it should only be a few lines of code plus any extra for the address validation.
Alternatively, you *may* be able to leave everything on defaults and add a Flask `before_request` handler to validate requests on the metrics endpoint, but I've never tried this so it may not work.

Let me know what you ended up doing or if you need any more info or help!
Thanks!

**Comment by fritjofbuettner** [comment]
Thanks for the reply. I ended up restricting access in the apache reverse proxy in the following way:

```
<Location "/metrics">
    Require ip <prometheus server ip>
</Location>
```

(The flask application is serverd by gunicorn in a docker container)
