### ISSUE TITLE
GunicornPrometheusMetrics Doesn't Export Python Metrics

### ISSUE THREAD

**Issue by mplachter** [rycus86/prometheus_flask_exporter#18]
When using `prometheus_flask_exporter` with `gunicorn` it seems that the built in metrics `(python_gc, memory, cpu, etc)` that are usually exported when just using this with the internal `flask` server does not get pushed to `/metrics`

**Comment by rycus86** [comment]
Thanks for reporting this! This is intentional as there won't be a single process metrics from the forked worker processes, so those default metrics are skipped.
I think this is the way it works elsewhere but I may be wrong.

Do you think it would make sense to have those metrics? And if yes, how?

**Comment by mplachter** [comment]
Hey @rycus86 this completely makes sense. 
I am curious if nothing can be exported either per worker (process) and then aggregated just like we do with the HTTP metrics or keep them separated by worker_id. I'm currently looking into the `python_client` directly and see what maybe can be done, if anything.

**Comment by mplachter** [comment]
@rycus86 I am going to close this for now.
It seems that the `gc_collector` and other metrics are disabled when `prometheus_multiproc_dir` is set as an environment variable.

https://github.com/prometheus/client_python/blob/master/prometheus_client/gc_collector.py#L20

I will move to a multithreaded WSGI server instead like `waitress` for now.
If this becomes a blocker and I choose to look deeper into prometheus client_python i'll let you know.

Thanks,

**Comment by rycus86** [comment]
@mplachter thanks a lot for digging into this and for reporting back!
I think I'm going to add a note to the README about this for anyone else wondering about the same thing.

Thanks!
