### ISSUE TITLE
Metrics per view function name instead of URL path?

### ISSUE THREAD

**Issue by nottrobin** [rycus86/prometheus_flask_exporter#2]
A new set of metrics for each path makes for a very noisy export, in our case. There could be literally thousands of paths.

Would it be possible to support tracking by the name of the function handling the request, rather than the path? Similar to what [django-prometheus](https://github.com/korfuri/django-prometheus) does.

So that the code:

``` python3
metrics = prometheus_flask_exporter.PrometheusMetrics(app)

@route('/<page_name>')
def process_page(page_name):
    # ...
```

Instead of outputting:

```
flask_http_request_duration_seconds_bucket{le="0.005",method="GET",path="/page1",status="200"} 0.0
flask_http_request_duration_seconds_bucket{le="+Inf",method="GET",path="/page1",status="200"} 1.0
...
flask_http_request_duration_seconds_bucket{le="0.005",method="GET",path="/page2",status="200"} 0.0
flask_http_request_duration_seconds_bucket{le="+Inf",method="GET",path="/page2",status="200"} 1.0
```

Would output:

```
flask_http_request_duration_seconds_bucket{le="0.005",method="GET",function="process_page",status="200"} 0.0
flask_http_request_duration_seconds_bucket{le="+Inf",method="GET",function="process_page",status="200"} 2.0
```

**Comment by rycus86** [comment]
Thanks for the examples! I'll have a look at the Django implementation then. I think we have two options here:

1. Add the view name as another label to the same metric
2. Create a new metric with view names, but without the http path

I'll check what people usually use/do in these cases and will try to do something similar.

Thanks!

**Comment by nottrobin** [comment]
No probs. I might try to submit a pull-request if I get a chance.

**Comment by nottrobin** [comment]
@rycus86 I added a pull-request ^ with a test. Let me know what you think of it.

**Comment by rycus86** [comment]
Thanks a lot! I haven't had time to look into it properly yet. The PR looks good, I'm just wondering if it's not too specific for your use case. I just want to check whether this could be done with existing overrides - even if so, the code might need some change to not add the `path` label by default if you dont want it.

I'll try to have a look later today.
Thanks a lot for the work so far!

**Comment by nottrobin** [comment]
It's your call, but I'm not sure it's that specific. As I say, this is how the django-prometheus package works.

It seems to me that there are basically 2 ways you can group request metrics, and by `request.endpoint` makes at least as much sense as `request.path`. Ultimately what you want to know with these metrics is which paths through your code are slow, so grouping by entrypoint (endpoint) seems to me exactly what most people would want in most cases (which is probably why this is what django_prometheus exposes).

I would say most applications will probably grow to the point where they are process at least hundreds of different URLs. Imagine a blog (probably the most common application for a website). Each post would have a new URL. And possible each category. Each post's page will take exactly the same path through the code, but they'll all have different URLs.

This verbosity in the output causes a significant problem - prometheus really can't easily handle parsing metrics that are thousands of lines long. It slows it down massively, and can quite easily crash it. So keeping the metrics as close to what you actually need to know is really quite important.

(I suppose you could say there is another way to group request metrics - by lumping them all in together. Some people might want to simply see the histogram of response times for all requests, not broken down at all. But maybe wait until someone asks before offering that final option.)

**Comment by rycus86** [comment]
OK, thanks, you sold it to me. :)
I'll do some minor styling edits and I'll publish a new version on PyPI today.
Thanks a lot for the contribution!

**Comment by nottrobin** [comment]
Amazing! Thanks @rycus86. Contributing to your project has been a dream.
