### ISSUE TITLE
Exceptions shouldn't bypass Flask's error handling

### ISSUE THREAD

**Issue by RazerM** [rycus86/prometheus_flask_exporter#24]
When an exception occurs in the view function, prometheus_flask_exporter turns it into a custom response, bypassing all of the Flask app's error handlers:

https://github.com/rycus86/prometheus_flask_exporter/blob/0203d62506a1119fa011c1b11036db95902d44c6/prometheus_flask_exporter/__init__.py#L456-L457

It gets returned from the function on this line:

https://github.com/rycus86/prometheus_flask_exporter/blob/0203d62506a1119fa011c1b11036db95902d44c6/prometheus_flask_exporter/__init__.py#L477

You could instead call [Flask.handle_user_exception](http://flask.pocoo.org/docs/1.0/api/?highlight=view_functions#flask.Flask.handle_user_exception). You can see where that's usually called [here](https://github.com/pallets/flask/blob/d3e1fed7773d1a85a9e2b434c375822edb904619/flask/app.py#L1897-L1912). It should also be called for `HTTPException`.

P.S. For non-error responses, `make_response` is called but isn't returned. This could be expensive (serializing a response, for example), so it should be returned rather than letting Flask call it again:

https://github.com/rycus86/prometheus_flask_exporter/blob/0203d62506a1119fa011c1b11036db95902d44c6/prometheus_flask_exporter/__init__.py#L472

**Comment by rycus86** [comment]
Wow, awesome, thanks again for the great suggestion! It seems to work very well and should be available in `0.8.0` in a few minutes.
