### ISSUE TITLE
Wiki: In Non Containerised approach, where is logs stored by default..? Can i overide the path?

### ISSUE THREAD

**Issue by deepak1725** [rycus86/prometheus_flask_exporter#27]
Please tell path where Metrics are stored by Default.

**Comment by rycus86** [comment]
Hi,

It is at `/metrics`, see https://github.com/rycus86/prometheus_flask_exporter/blob/master/README.md#configuration

**Comment by deepak1725** [comment]
That's HTTP  endpoint.  i was asking Path, where metrics are actually stored in Backend.
I guess its `/tmp/*` by default
To override default path: I just did: 
`export prometheus_multiproc_dir=/home/my_name/prom_logs`
 and hence able to export to required place.

**Comment by rycus86** [comment]
Oh, that path. Yes, that environment variable is used by the underlying Prometheus library to store temporary files to aggregate over when in multiprocessing mode.
Not sure what's the default value of that or if it has one. I believe, if you want to enable multiprocessing, you should set that like you did.

**Comment by deepak1725** [comment]
thanks!
