### ISSUE TITLE
Wiki: Need to add parameter in labels

### ISSUE THREAD

**Issue by deepak1725** [rycus86/prometheus_flask_exporter#28]
What is recommended way for adding Parameter in metrics... ?

I mean, Currently we have:
`invocation_by_type_created{item_type="hey"} 1.5603457069620097e+09`
Which can be achieved by: 
```
@metrics.counter('invocation_by_type', 'Number of invocations by type',
         labels={'item_type': "hey"})
def echo_status(status):
    return 'Status: %s' % status, status
```
Now,  We need to have some **timedelta** included in output metrics,
something like:
`invocation_by_type_created{item_type="hey", timedelta=52} 1.5603457069620097e+09`

which is ofcause the function execution time..

**Comment by rycus86** [comment]
Hm, not sure I understand it completely, sorry.
If you want count and duration, have a look at summary or histogram. Those would aggregate the total invocation times on the endpoint.
Does this help?

**Comment by deepak1725** [comment]
Okay.. Is there a way to edit metrics..? During or after a function call..?

**Comment by rycus86** [comment]
Edit in what way? Can you give me examples of what you're trying to achieve?

**Comment by deepak1725** [comment]
Ok, Lets suppose we got a metrics generated by:
```
@metrics.counter('invocation_by_type', 'Number of invocations by type',
         labels={'item_type': "foo"})
def echo_status(status):
    return 'Status: %s' % status, status
```
Now can i reference that meterics generated above..?
I need to Edit same metrics to add some additional data.

**Comment by rycus86** [comment]
You cam have more than one labels, and they accept functions or lambdas for values that are evaluated in the request context. See usage at https://github.com/rycus86/prometheus_flask_exporter/blob/master/README.md#usage

Is this what you're after?

**Comment by deepak1725** [comment]
Thanks! It helped
