### ISSUE TITLE
Adding default label

### ISSUE THREAD

**Issue by tcmalyousef** [rycus86/prometheus_flask_exporter#30]
Hi,

I'm kind of new to Prometheus, so my usage might not be the best approach.

I have multiple flask applications and monitored within the same Prometheus. I want to be able to filter using application_name label.

I want to add `application_name` label to the default exports. what is the best way to approaching this?

I tried the following:

```python
metrics = GunicornPrometheusMetrics(app, export_defaults=False)
metrics.info('app_info', 'Application info', version=app_info.get('version', '0.0.0'), app_name=app_name)
...
...
@app.route("/")
@metrics.do_not_track()
@metrics.summary('requests_by_status', 'Request latencies by status',
                 labels={'status': lambda r: r.status_code, 'app_name': app_name})
@metrics.histogram('requests_by_status_and_path', 'Request latencies by status and path',
                   labels={'status': lambda r: r.status_code, 'path': lambda: request.path, 'app_name': app_name})
@metrics.counter('invocation_by_type', 'Number of invocations by type',
                 labels={'item_type': lambda: request.view_args['type'], 'app_name': app_name})
def index():
...
```
same decorators are replicated on each route.

But I get the following error:
```
ValueError: Duplicated timeseries in CollectorRegistry: {'requests_by_status_count', 'requests_by_status_sum', 'requests_by_status', 'requests_by_status_created'}
```

Any help is appreciated!

**Comment by rycus86** [comment]
Hi,

Yeah, that makes sense to me. But I'm not sure whether we can do this with this library already or not, I can check it over the weekend.
If we can't do it yet, it's probably a small change to add. :)

Thanks!

**Comment by rycus86** [comment]
I haven't managed to spend time on this yet, but wanted to ask whether exposing multiple different metrics endpoints could work for you? In that case, Prometheus would attach the "where it came from" extra label anyway that would allow you to filter by it.

As for the error above, the `@metrics.do_not_track()` disables collecting the default metrics from that function, but it doesn't prevent setting up that metric. `PrometheusMetric(..., export_defaults=False)` would skip that step, if that's what you want to do.

Still, adding a label to each of the metrics *could* be a feature, not sure if very efficient though, so I'm interested to hear whether you think you'll need this, or whether you're exploring alternative options.

**Comment by rycus86** [comment]
I had a look at this, and it was relatively easy to add, so there's now a new `static_labels` argument on `PrometheusMetrics(..)` and you can use it like this:

```
# use static_labels here
metrics = GunicornPrometheusMetrics(app, static_labels={app_name=app_name})
metrics.info('app_info', 'Application info', version=app_info.get('version', '0.0.0'))
...
...
@app.route("/")
@metrics.summary('requests_by_status', 'Request latencies by status',
                 labels={'status': lambda r: r.status_code, 'app_name': app_name})
@metrics.histogram('requests_by_status_and_path', 'Request latencies by status and path',
                   labels={'status': lambda r: r.status_code, 'path': lambda: request.path, 'app_name': app_name})
@metrics.counter('invocation_by_type', 'Number of invocations by type',
                 labels={'item_type': lambda: request.view_args['type'], 'app_name': app_name})
def index():
...
```
