### ISSUE TITLE
wiki: How to reset Counter..?

### ISSUE THREAD

**Issue by deepak1725** [rycus86/prometheus_flask_exporter#32]

**Comment by rycus86** [comment]
Can you give some more information?
What are you trying to achieve?

**Comment by deepak1725** [comment]
@rycus86 I actually need to reset `*request_count_total*` in `/metrics` endpoint. So any way to achieve same..?

**Comment by rycus86** [comment]
Counters in Prometheus shouldn't decrease, they can only reset when the process restarts. See https://www.robustperception.io/how-does-a-prometheus-counter-work for more information.

You could probably use a Gauge metric and increment / set to zero as needed if you want?

**Comment by deepak1725** [comment]
Okay. How can Push Gauge Metrics to Zero..?

**Comment by rycus86** [comment]
I'd recommend using the underlying Prometheus library's Gauge directly, and this Flask extension will expose it on the same metrics endpoint as usual. See their docs on gauges at https://github.com/prometheus/client_python/blob/master/README.md#gauge

**Comment by deepak1725** [comment]
Thanks! It helped
