### ISSUE TITLE
Exclude swagger requests

### ISSUE THREAD

**Issue by skecskes** [rycus86/prometheus_flask_exporter#35]
I just started this on clean flask app and my metrics are already polluted by many swagger mnetrics. How can I exclude endpoints which are not exposed by me, but as middleware through flask?

![Screen Shot 2019-09-10 at 11 31 53](https://user-images.githubusercontent.com/3411329/64606741-d7d7c580-d3be-11e9-9d73-a2ba75ad71fb.png)

**Comment by rycus86** [comment]
That's a good question, I haven't considered it. Internally, I check if the Flask `request` has a `prom_do_not_track` attribute, and will not apply the default metrics collectors if it does.
See https://github.com/rycus86/prometheus_flask_exporter/blob/master/prometheus_flask_exporter/__init__.py#L532 and https://github.com/rycus86/prometheus_flask_exporter/blob/master/prometheus_flask_exporter/__init__.py#L299

If you can set this attribute for each Swagger request in a middleware or somehow else, that should work around this problem.

Does this help?

**Comment by rycus86** [comment]
I merged a fix for this, you can now use either:
```python
PrometheusMetrics(excluded_paths='/swagger')
```
or if you have multiple different patterns:
```python
PrometheusMetrics(excluded_paths=['/swaggerui', '/swagger.json'])
```

Let me know if this helps!
