### ISSUE TITLE
flask_http_request_total counter value is not constantly increasing

### ISSUE THREAD

**Issue by 4n4nd** [rycus86/prometheus_flask_exporter#38]
We have a simple flask [application](https://github.com/HumairAK/anomaly-detection-demo-app/blob/master/app/__init__.py#L43) where we are creating an instance of `PrometheusMetrics`. The metrics page seems to be working fine, but the metric value for `flask_http_request_total` doesn't seem to be monotonically increasing.

The graph for that metric looks like:
https://snapshot.raintank.io/dashboard/snapshot/NOAZB2Av46GV8Tk26heedJcE6IR4T118

Thanks

**Comment by rycus86** [comment]
Hi @4n4nd
Based on the repo you linked, it looks like you use Gunicorn for your app?
That needs multiprocessing support from the Prometheus library, and this exporter has some helpers to do that, check it out: https://github.com/rycus86/prometheus_flask_exporter/blob/master/README.md#multiprocess-applications

Let me know if this helps!

**Comment by rycus86** [comment]
> the metric value for flask_http_request_total doesn't seem to be monotonically increasing

You're probably hitting different Gunicorn worker instances of the app,this is why the value would not be monotonic.

**Comment by 4n4nd** [comment]
Oh that makes a lot of sense, I never really thought about it.
Thanks!
