### ISSUE TITLE
Prometheus Flask exporter with __main__

### ISSUE THREAD

**Issue by klml** [rycus86/prometheus_flask_exporter#40]
I want to use Prometheus Flask exporter with [\_\_main__](https://docs.python.org/3.5/library/__main__.html).

This works fine by running env FLASK_APP=app.py flask run --port=80 --host='0.0.0.0':

```
from flask import Flask
from prometheus_flask_exporter import PrometheusMetrics

app = Flask(__name__)
metrics = PrometheusMetrics(app)

app.debug = True

@app.route("/", methods=['GET'])
def index():
    return "hello world"
```
But I want to use my app in \_\_main__, running python app.py.

```
from flask import Flask
from prometheus_flask_exporter import PrometheusMetrics

app = Flask(__name__)
metrics = PrometheusMetrics(app=None, path='/metrics')

app.debug = True

@app.route("/", methods=['GET'])
def index():
    return "hello world"

if __name__ == '__main__':
    metrics.init_app(app)
    app.run(host='0.0.0.0', port=80)
```

Here I get 400 on /metrics.

I got no clue how to init metrics correctly.

thx for helping
klml

PS I asked this already [stackoverflow.com](https://stackoverflow.com/questions/58432408/prometheus-flask-exporter-with-main), but got  no answer.

**Comment by rycus86** [comment]
Hm, not at a computer right now but that looks OK.
Can you try without setting the debug mode on?
I wonder if that's what's breaking it.

**Comment by ampedandwired** [comment]
Can confirm that the debug flag seems to break things. If I put the following in `app.py` and run with `python app.py` then I see the metrics page successfully at http://127.0.0.1:5000/metrics

```python
from flask import Flask
from prometheus_flask_exporter import PrometheusMetrics
app = Flask(__name__)
metrics = PrometheusMetrics(app=app)
app.run(debug=False)
```

But change `debug=False` to `debug=True` and I get a 404. This is with `prometheus-flask-exporter==0.11.0`.

**Comment by rycus86** [comment]
Thanks a lot for the investigation!
I'll try to have a look when I can.

**Comment by rycus86** [comment]
Do you want to try with the `DEBUG_METRICS` environment variable set?
https://github.com/rycus86/prometheus_flask_exporter/blob/master/README.md#debug-mode

**Comment by klml** [comment]
@rycus86 thx for your lightspeed responses;)

I tried DEBUG_METRICS and it suddenly worked.
It even does not depend if DEBUG_METRICS is true or false. 
It only must be set.
Vice versa, with no DEBUG_METRICS at all, I get "my" 404.

First I tried without DEBUG_METRICS and got a 404, but I got 200 be only setting DEBUG_METRICS.

```
root@ocpdevc001 [0] :/home/klml/python-ocp-demo
# echo $DEBUG_METRICS

root@ocpdevc001 [0] :/home/klml/python-ocp-demo
# python3 app.py 
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 780-306-174
10.12.69.235 - - [04/Nov/2019 10:13:23] "GET /metrics HTTP/1.1" 404 -


root@ocpdevc001 [0] :/home/klml/python-ocp-demo
# export DEBUG_METRICS=false
root@ocpdevc001 [0] :/home/klml/python-ocp-demo
# python3 app.py 
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 780-306-174
10.12.69.235 - - [04/Nov/2019 10:13:37] "GET /metrics HTTP/1.1" 200 -

```

So I got a workaround;) 

Thx
klml

**Comment by rycus86** [comment]
Nice one! I do remember debug mode was a bit hacky, so it looks like that extra environment variable is necessary. :(
You're right, the value doesn't matter, it just needs to be set.

**Comment by ampedandwired** [comment]
Thanks for the quick response. Running with `DEBUG_METRICS=true` fixes the problem.

**Comment by klml** [comment]
@rycus86 Should we mention the dependence  `DEBUG_METRICS=true/false` working with `__main__` somewhere in README.md? 

btw: it works even with `DEBUG_METRICS=lorem` ;)

**Comment by rycus86** [comment]
I think it's not about `__main__` but rather the Flask debug mode, see https://github.com/rycus86/prometheus_flask_exporter/blob/master/README.md#debug-mode

**Comment by rycus86** [comment]
Closing this for now, feel free to reopen or submit a PR if you think the docs need updating. Thanks!

**Comment by glebignatieff** [comment]
If you already use `FLASK_DEBUG`, then you can simply assign `DEBUG_METRICS` to it in your `.flaskenv`:
```sh
DEBUG_METRICS=${FLASK_DEBUG}
```
