### ISSUE TITLE
Need help with a simple use case using Counter

### ISSUE THREAD

**Issue by julienMichaud** [rycus86/prometheus_flask_exporter#43]
Hi, 

Im very new to Flask and Python in general. 
I would like to expose metrics of a simple app I created. 

The thing is I don't understand how to increment the value of a Counter for example.. 

```
@app.route('/newaliment', methods=['GET', 'POST'])
@login_required
@metrics.counter('aliments', 'number_of_aliments_added')
def newaliment():
    form = AlimentsForm()
    if form.validate_on_submit():
        aliment = Aliment(aliment_name = form.aliment_name.data, description =form.description.data, author=current_user )
        db.session.add(aliment)
        db.session.commit()
        flash('Congratulations, you added a new aliment !')
        return redirect(url_for('newaliment'))
    return render_template('newAliment.html', title='NewAliment', form=form)
```

I initialize my counter but how can I increment it by "1" when an aliment is added in my database please ? 

Thanks for your help and excuse my stupid question.

**Comment by rycus86** [comment]
Hi! No need to apologize, this is a completely valid question!

This library provides decorators for your Flask managed endpoints, e.g. the `@metrics.counter` will count the number of times your `/newaliment` has been called. If you want to keep track of a different counter and manage it yourself, you could get a `Counter` from the underlying library like this (double-check if I haven't messed up the syntax) : 

```python
from prometheus_flask_exporter import Counter

my_counter = Counter('name', 'description')

    ...
    db.session.commit()
    my_counter.inc()
```

Does this help?

**Comment by julienMichaud** [comment]
Make total sense, thanks for your help and best of luck with the fires in your country !
