### ISSUE TITLE
usage of flask_exporter_info

### ISSUE THREAD

**Issue by DeoLeung** [rycus86/prometheus_flask_exporter#47]
Hi, I would like to make use of this metrics to count the active workers under gunicorn.

I use the app pattern but found that when the gunicorn re-spawn a new worker, the `pid` of the old one still being export, would you give me some idea how to achieve the counting or remove the old `pid` from the metrics?

**Comment by rycus86** [comment]
Hi, that sounds like a tricky one. 🙂

Don't know a definite answer, but you could perhaps try a metric with a randomly generated tag set on startup, perhaps uuid, then count the unique active metrics of those. Not sure how to determine if the metric is still alive, but perhaps if you define it as a counter and set it to the current time for example, then you could detect when it stops increasing?

These are just ideas, let me know if it helps!

**Comment by DeoLeung** [comment]
I came up with something like this
```python
    from prometheus_flask_exporter.multiprocess import \
      GunicornInternalPrometheusMetrics
    metrics = GunicornInternalPrometheusMetrics(app=app_, group_by='url_rule')
    labels = {'pid': os.getpid()}
    metrics.register_default(
        metrics.counter('flask_http_request_count',
                        'total request count of the current process',
                        labels=labels))
```
and with the prometheus query
```promql
count(delta(flask_http_request_count_total[1m])>0)
```
most of the time is ok, when spawning a process may see a few extra counts for a minute(since I scrape it every 5s, the counter just keeps increasing until `max_requests`)

**Comment by rycus86** [comment]
Sounds good, assuming PIDs are not reused too often. 🙂 Good trick! :+1:

**Comment by rycus86** [comment]
Closing this now, but feel free to comment/reopen if you have any further questions on this. Thanks!
