### ISSUE TITLE
Share `metrics` object across modules

### ISSUE THREAD

**Issue by trallnag** [rycus86/prometheus_flask_exporter#48]
Hello, my API is spread across several Blueprints and namespaces while the `metrics` object gets instantiated in my main `app.py`. Is there a built-in way to share the object across modules, maybe something like `current_app` in Flask?

`app.py`
```python
import api.internal
import api.external

app = Flask(__name__)
metrics = GunicornPrometheusMetrics(app)
```

I have seen the app factory example, but there everything is set up in its own `app_setup.py`. But I cannot import `app.py` in my APIs as this would introduce circular dependencies.

Am I missing something (as a beginner) or should I just create a "singleton" method somewhere?

```python
metrics = None

def get_current_metrics(app):
    global metrics

    if metrics is None and app:
        metrics = GunicornPrometheusMetrics(app)
        
    return metrics
```

Thanks in advance

**Comment by rycus86** [comment]
Hi,
I don't have a definite answer for you, but can try to have a look if your code ia public.
Otherwise, I'd still try the app factory pattern probably, where you could have one module creating a metrics object with `None` as the app, then call `init_app` later from the module that creates it? You do have one Flask app object right, if I got that correctly?
I'm not a 100% app factory with `init_app` actually works with the Gunicor  flavour, so please let mw know how you get on! Thanks!

**Comment by trallnag** [comment]
Thanks for the answer, I just did it like proposed in my initial post and it seems to work fine.

On another note, you've made a pretty cool exporter and I like the decorator approach. New to me, always though the `@` were just annotations like in Java :grin:.. far from that. One can even use it apart from instrumenting the Flask API

**Comment by rycus86** [comment]
Thanks for the kind words, and I'm glad you've found a solution! :+1:

**Comment by salapat11** [comment]
@trallnag, my APIs are spread across multiple namespaces and files.  Can you share how you got around sharing the metrics object across each API file?  I am having challenges passing the Flask application object that is required to initialize metrics.

**Comment by trallnag** [comment]
@salapat11, create a file `telemetry.py` (or use the `__init__.py`, whatever) where you use the app factory pattern just like @rycus86 recommended. 

```python
from prometheus_flask_exporter import PrometheusMetrics
METRICS = PrometheusMetrics.for_app_factory()
```

In your module where you create the "root" Flask object: 

```python
from telemetry import METRICS
# ...
METRICS.init_app(flask_app)
```

In all other modules where you want to use the metrics object:

```python
from telemetry import METRICS
```

**Comment by salapat11** [comment]
@trallnag , thanks for taking time to answer my question.  I was able to initialize the metrics object using the factory pattern with the example provided.  I imported the metrics object in the module I want to use and added a counter.
`from telemetry import metrics`
`@metrics.counter('user_count', 'number of users', labels={})`
I can see TYPE and HELP for "user_count" on the metrics page but the counter never gets incremented
# HELP user_count_total Total number of users
# TYPE user_count_total counter

Any ideas?

**Comment by rycus86** [comment]
Maybe it's an obvious question, but have you requested the endpoint you put the decorator on?

**Comment by salapat11** [comment]
I see the issue now.  I had the decorator at the class level instead of the method level.  It works as expected.  Thanks again for your time @rycus86 , @trallnag .

Thanks for putting this library, @rycus86 .  Very easy to integrate and got it working in few mins.
