### ISSUE TITLE
control metrics

### ISSUE THREAD

**Issue by jichu20** [rycus86/prometheus_flask_exporter#50]
Hi.
Is it possible to use the library to generate metrics within methods and not just as annotations?

Thanks!!

**Comment by rycus86** [comment]
Hi, I *think* you can put decorators on regular methods too, not only on Flask request handlers, but I'm not a  100% sure - a quick test would tell.

You can't use them within methods or as variables to set/increment if I remember correctly, but if you use `prometheus_client` objects like Counter or Gauge, those metrics would be exported by this library automatically too.

Does this help?

**Comment by jichu20** [comment]
hi i have tried to use the prometheus client directly and the metric is exported correctly.

Thank you
