### ISSUE TITLE
Love the tool, but one big problem, disk usage

### ISSUE THREAD

**Issue by posix4e** [rycus86/prometheus_flask_exporter#53]
I filled up my drive with gauges and counters without any other than the default configuration. It's for a very busy website and we blew through 10GB of space in one day on every node. Perhaps I have configured something incorrectly?

**Comment by rycus86** [comment]
Hi! Sorry to hear that! Do you know what filled up your disk? My guess would be multiprocessing files that keep metrics combined on the same machine, and if that's the case, we can look into trying to handle that somehow.
If not, then could you share some details about your configuration to work out what could have gone wrong?
Thanks!

**Comment by posix4e** [comment]
Actually i bet it's because I'm using multiple workers and GEVENT.

**Comment by posix4e** [comment]
So i switched to just a normal synchronous worker. I'm curious when should I clean up these logs? Do I need to terminate my gunicorn? Perhaps gunicorn could handle deleting some of the files?

**Comment by rycus86** [comment]
Can you add some more details? Perhaps this is something that should be called out in the README.
We can also try to work on a fix to avoid this problem, I'm just not sure I get the context and how to reproduce it.

Also, have you checked the https://github.com/prometheus/client_python library perhaps to see if they saw the same problem with Gevent and if they worked anything out for it?

**Comment by rycus86** [comment]
Closing this old issue, but feel free to open a new issue (or reopen this one) if you find any new information on this!
