### ISSUE TITLE
_total suffix getting added to metric.counter

### ISSUE THREAD

**Issue by rohanmohapatra** [rycus86/prometheus_flask_exporter#55]
```
metrics.register_default(
    metrics.counter(
        'by_path_counter', 'Request count by request paths',
        labels={'path': lambda: request.path}
    )
)
```
When I try doing this, the metric comes as `by_path_counter_total`, I don't understand why that is happening?

**Comment by rycus86** [comment]
We get this from the official Prometheus client library, see https://github.com/prometheus/client_python/blob/master/README.md#counter

> If there is a suffix of _total on the metric name, it will be removed. When exposing the time series for counter, a _total suffix will be added. This is for compatibility between OpenMetrics and the Prometheus text format, as OpenMetrics requires the _total suffix.

**Comment by rohanmohapatra** [comment]
Thanks
