### ISSUE TITLE
I want to pass a metric to the gauge

### ISSUE THREAD

**Issue by rohanmohapatra** [rycus86/prometheus_flask_exporter#56]
How to create a gauge metric for a value?

**Comment by rycus86** [comment]
From the example in the README at https://github.com/rycus86/prometheus_flask_exporter/blob/master/README.md#usage

```
@app.route('/long-running')
@metrics.gauge('in_progress', 'Long running requests in progress')
def long_running():
    pass
```

**Comment by rycus86** [comment]
Closing this old issue, but feel free to open a new one if you have any problems or questions!
