### ISSUE TITLE
Unable to have common metric key with labels to separate type over different routes

### ISSUE THREAD

**Issue by warmfusion** [rycus86/prometheus_flask_exporter#58]
Setup;
1. Two (or more) API handling methods with their own routes
2. metric registered with common name `auditls_api`
3. use of `type: label` to separate values in prometheus later

``` python
@app.route("/api/v1/dns/<target>", methods=["GET"])
@metrics.counter('auditls_api', 'API Calls for DNS information',
         labels={'type': 'dns', 'target': lambda: request.view_args['target']})
def get_dns(target):
  #do athing

@app.route("/api/v1/http/<target>", methods=["GET"])
@metrics.counter('auditls_api', 'API Calls for HTTP response information',
         labels={'type': 'http', 'target': lambda: request.view_args['target']})
def get_http_status(target):
   # do different thing
```

## Expected

Metrics are collected for each API route, and exposed to prometheus such that I might do queries like  `sum by (type)(rate(autidls_api_total[5m])` so I can view the relative distribution over all the `types` of API call being handled.

At the moment, it seems the proposed implementation is to have `auditls_api_by_dns_total` and `auditls_api_by_http` as seperate metrics, but i can't then group those back together.

## Actual

Error: `2020-06-24T12:25:00.277947666Z ValueError: Duplicated timeseries in CollectorRegistry: {'auditls_api_created', 'auditls_api_total'}
`

---

Do you have any guidance on what I should be doing here?

**Comment by rycus86** [comment]
Hi @warmfusion ,

Prometheus doesn't support declaring the same metric twice, that's why you get the error. Arguably, this library could help you merge them together, but I'm not sure the underlying client library supports that, I can have a look.

For your particular use case, you should be able to do this just like the the README suggests:

> If you want to apply the same metric to multiple (but not all) endpoints, create its wrapper first, then add to each function.

```
app = Flask(__name__)
metrics = PrometheusMetrics(app)

by_path_counter = metrics.counter(
    'by_path_counter', 'Request count by request paths',
    labels={'path': lambda: request.path}
)

@app.route('/simple')
@by_path_counter
def simple_get():
    pass
    
@app.route('/plain')
@by_path_counter
def plain():
    pass
```

Does this help?

**Comment by rycus86** [comment]
Closing this old issue, but feel free to reopen (or open a new one) if you have any problems or questions!
