### ISSUE TITLE
adding account info into labels

### ISSUE THREAD

**Issue by bilalbayasut** [rycus86/prometheus_flask_exporter#60]
setup:
1. using make_app() factory pattern

question:
1. I want to add a label containing account_id :
```
def make_app():
   metrics._static_labels = {"account_id": current_user.id}
   metrics.init_app(app)
   return app
```
but obviously, I get `current_user` :`None` because metrics.init_app(app) and make_app() is called before the app get account info .

any idea on how to set label containing account_id in make_app() ?

I have tried using `lambda: request.account.id` but it doesn't give me the result, rather it gave a function object

1. I have tried using `lambda: request.account.id` -> returns `<function make_app.<locals>.<lambda> at 0x7f28b6d4b730>`
2. tried `PrometheusMetrics(app, group_by=custom_rule)` -> but this is about we add another default metrics, not a label.

**Comment by rycus86** [comment]
The static labels are static at the moment unfortunately. Are you trying to add this label to ALL metrics in this app?

You could also consider a default metric to apply to all endpoints:
```python
metrics.register_default(
    metrics.counter(
        'by_account_counter', 'Request count by account IDs',
        labels={'account_id': lambda: current_user.id}
    )
)
```

Does this help?

**Comment by bilalbayasut** [comment]
thank god, I think I'm crazy, yes it is static , there is no other way, yet. thanks for responding @rycus86 . the default metric unfortunately is less usable in my case, because I want to filter based on account_id in my metric in grafana later on

**Comment by rycus86** [comment]
I guess we could look at supporting lambdas in static labels (default labels maybe?), can't remember now why I made them static initially, but if it's easy to change that I'm happy to try.

**Comment by rycus86** [comment]
Had a look at the code, I think it can work with potentially not too many changes. I'll see if I can find some time this weekend to have a go at it.

**Comment by bilalbayasut** [comment]
yes, adding our own default labels will be extremely useful. so that user can filter out their metric based on label ie {account_id: 123}. btw, thanks , its beautiful lib

**Comment by rycus86** [comment]
Managed to make this work now, the `account_id: lamdba: request.account.id` form should work.
Also renamed `static_labels` to `default_labels` (though the former will still work).

Hopefully this helps!

**Comment by bilalbayasut** [comment]
thank you, you rock! @rycus86
