### ISSUE TITLE
No metrics access

### ISSUE THREAD

**Issue by Younes-Benotmane** [rycus86/prometheus_flask_exporter#65]
Hi, does anyone have any idea how to use this export with more than one object.
Like in this example:
```
app = Flask(__name__)
app.config['JSONIFY_PRETTYPRINT_REGULAR'] = True
bot_server_webhook = Blueprint('bot_server_webhook', __name__, url_prefix='/webhooks/chatroom')
CORS(bot_server_webhook)
server_webhook = Blueprint('server_webhook', __name__)
CORS(server_webhook)
```
the access to the api is operational via resources. But when I try to add resources for monitoring (URL/metrics). I don't have access to anything
it's for an api contained in docker. I'm not a developer, I'm an admin sys. If anyone has an idea i'm interested.

**Comment by rycus86** [comment]
Can you tell what have you tried so far?
I assume `PrometheusMetrics(app)` and that didn't work?

If you explain what URLs belong to the app and what URL do you want the metrics endpoint on, we should be able to set up an example to verify the setup that works.
I don't know off the top of my head how is this supposed to work with multiple Blueprints, but happy to try and help you find out.

**Comment by Younes-Benotmane** [comment]
Thank you for the prompt response rycus86.
- Yes, I have already tried removing the blueprints and using the objey app.
I didn't code the app. So I have to adapt the probe to work with it.
- I tried to export again but I get a 404 error each time. If I put in the original code without adding probes would that help ?
I also checked the orders to be added. But nothing to do. When I try to access the metrics resource it tells me that nothing is accessible.

**Comment by rycus86** [comment]
You could try registering it on one of the blueprints (or a dedicated blueprint) by skipping the original metrics endpoint with `metrics = PrometheusMetrics(app, path=None)` then calling `metrics.register_endpoint('/metrics', blueprint)` to see if this works, I'm not a 100% sure.
If it doesn't work, I'll try to set up a minimal example when I can.

As a side note: what URL does your Prometheus instance scrape? Is it the default `/metrics` ?

**Comment by Younes-Benotmane** [comment]
thank you for your help, rycus. But I found another solution by going through another export available on pipy (knotty). I didn't need to create any metrics. I simply removed the 2 blueprints to replace them by app and copy-paste the available code.
Thanks again.

**Comment by rycus86** [comment]
I'm glad it all worked out for you! 👍
