### ISSUE TITLE
Add a custom function timer metric for flask restplus

### ISSUE THREAD

**Issue by shakeel-appyhigh** [rycus86/prometheus_flask_exporter#70]
Hi,
I have an ML model deployed on Flask restplus which classifies incoming text and also adds some other data  through simple utility functions(without using the ML model). They are running at the same endpoint. I was able to run the default metrics and view them in in built prometheus dashboard and also grafana. But I also want to view a histogram of the time each of the functions take to process the request. Is it possible to make a histogram for viewing the time taken to process the request at the same endpoint but at different points within that endpoint?

I want to do something like: 
```
start = time.time()
//ml inference
end = time.time()
//histogram plot(end-start, default buckets)

start = time.time()
//utility functions
end = time.time()
//histogram plot(end-start, default buckets)

```
and view these plots on the grafana dashboard.

**Comment by rycus86** [comment]
Hi,

If you want to measure something that is not a Flask view function, you can use the underlying Prometheus client library, and you'll get them automatically exposed on the same metrics endpoint. See https://github.com/prometheus/client_python#histogram how to add a Histogram with that library.

Hope this helps?

**Comment by shakeel-appyhigh** [comment]
Thank you. It works. Your repository is amazing.
