### ISSUE TITLE
No auto-expositioned exceptions summary for endpoints?

### ISSUE THREAD

**Issue by deepbrook** [rycus86/prometheus_flask_exporter#72]
Great library! I'm curious why exceptions in endpoints aren't auto-expositioned as well, though ?

I'd like to use this lib, but the prospect of having to add an exception summary metrics on each of my endpoints kinda sucks (I'm exceptionally lazy).

Any reason for skipping this in the defaults? If no, I can supply a PR to add it.

Cheers!

**Comment by rycus86** [comment]
Thanks @deepbrook !
Yeah, I haven't thought of that. You should be able to configure default metrics (though I'm not totally sure if you can extract the exception in the lambda to provide the label value).
If you have time, I'd be happy to look at a PR adding default support for it. 👍

**Comment by deepbrook** [comment]
Alright, I'll have a look. While we're at it: The total requests per endpoint are not tracked by default either, is that true?
Is that something you'd merge as well? There's not much point in tracking total requests to the app if I can't filter by endpoints, imo.

**Comment by rycus86** [comment]
Hm, yeah haven't really thought of that either, it's interesting no one else wanted it so far. I guess you can get it from the counter part of the histogram at `flask_http_request_duration_seconds` if I remember correctly.

**Comment by deepbrook** [comment]
Really? Odd. RED metrics are pretty much *the* metrics to have when monitoring a web app, if nothing else. I'm prepping a PR atm, hopefully it's useful.

**Comment by rycus86** [comment]
This is now released in version `0.16.0`
