### ISSUE TITLE
Can't pass a registry to `GunicornInternalPrometheusMetrics` consturctor.

### ISSUE THREAD

**Issue by boarik** [rycus86/prometheus_flask_exporter#75]
Issue: getting `TypeError: __init__() got multiple values for keyword argument 'registry'` when trying to create a `GunicornInternalPrometheusMetrics` while providing the `registry` keyword argument.

If I'm not mistaking, providing a registry in the constructor call to  `MultiprocessPrometheusMetrics` will cause this error for any attempt such attempt, since we pass to the `super.__init__` call both `registry=registry` and the `**kwargs` values.

https://github.com/rycus86/prometheus_flask_exporter/blob/9cafda7cb1e43d31ad26ffeeb0dfe775bff86ea9/prometheus_flask_exporter/multiprocess.py#L53-L58

**Comment by rycus86** [comment]
Version `0.16.1` is building now and will be released once finished.
That will include the fix for this.

Thanks again @boarik !

**Comment by boarik** [comment]
Pleasure :)
