### ISSUE TITLE
Version mismatch between GitHub and PyPI

### ISSUE THREAD

**Issue by bburtin** [rycus86/prometheus_flask_exporter#77]
I think there may be a version mismatch between GitHub and PyPI.  PyPI lists prometheus_flask_exporter at version 0.16.4, but **setup.py** at the tip of master specifies that the version is 0.16.1.  Is this intentional?

**Comment by rycus86** [comment]
Thanks a lot for letting me know! I had some trouble getting the deploy through Travis, looks like I forgot to bump the version number properly. I'll release a new version later.

**Comment by bburtin** [comment]
No problem.  I really appreciate your support of this package!  It makes it really easy to collect metrics from a Flask server.

**Comment by rycus86** [comment]
`0.16.5` is building now on Travis, then this should be sorted out hopefully. Thanks again!
