### ISSUE TITLE
Increased P99 latency

### ISSUE THREAD

**Issue by johri21** [rycus86/prometheus_flask_exporter#79]
I am using `GunicornInternalPrometheusMetrics` for capturing Flask metrics from our application. 
As stated in the documentation I added the below code:
```
from prometheus_flask_exporter.multiprocess import GunicornInternalPrometheusMetrics


def child_exit(server, worker):
    GunicornInternalPrometheusMetrics.mark_process_dead_on_child_exit(worker.pid)
```
And initialized `GunicornInternalPrometheusMetrics` on our main server.py file. Post doing it and deploying on production the P99 latency rose as can be seen in the graph. The plateau is the increased latency while the deployment took place. We reverted the deployment later.

Note: We have another argus dashboard that monitors the latency of this API. The graph is that data.

What can the issue be? Is this expected?

<img width="1664" alt="Screen Shot 2020-09-09 at 16 51 32" src="https://user-images.githubusercontent.com/2655795/92600536-c3bdf100-f2bc-11ea-858b-8994746fd5ba.png">

**Comment by rycus86** [comment]
@johri21 did you work out what happened?

**Comment by johri21** [comment]
@rycus86 Yes, it was because of some other issue, a library update happened which caused the increased the latency
