### ISSUE TITLE
Measuring resource consumption by endpoints

### ISSUE THREAD

**Issue by Drvanon** [rycus86/prometheus_flask_exporter#80]
Hi, thank you so much for this project. It has already lead to so much insight into our application even though my understanding of the whole flask-exporter, prometheus, grafana stack is very minimal. 

At the moment I am trying to analyse the resource consumption per endpoint in our application and I am not really sure how to go about this. For context: I am using a gunicorn server behind nginx hosting a flask application. I have read some articles that it is not trivial to set up prometheus in a way that it reads out useful information, because the whole program/library/function per thread setup falls away in python. 

My approach to this would be to create a test instance of our server and dedicate a few computers to bombarding only one endpoint and seeing the general metrics of the server change because of it. This is a rather indirect method, so it would be much nicer if there would be a way that I could measure it directly. 

I am not really clear if this is mostly a gunicorn issue or not. If that is the case it would not be much of a problem to switch to something else.

**Comment by rycus86** [comment]
Hi @Drvanon - thanks for the kind words! 👍

Measuring per-thread or per endpoint CPU stats mihht be hard in Python, I agree. Your approach sounds like one where you could experiment, see what results it would give you.

An alternative could be running a single instance on a server with not too many other things running next to it, then hit the same endpoint 10/100/1000 times and see the total process CPU time. Then hit another endpoint the same amount and record the process CPU time increase. This way you could get a relative "cost" of endpoints - of your goal is to find the most CPU expensive calls.

Does this help?

**Comment by Drvanon** [comment]
It does help in the sense that I now know that I shouldn't look much further, or expect that it would be a simple solution, though I am a bit disappointed that there is not a "real" way of solving this.
