### ISSUE TITLE
How to secure the scrape endpoint?

### ISSUE THREAD

**Issue by riyadparvez** [rycus86/prometheus_flask_exporter#81]
As the title says, how to secure the endpoint with package like Flask-HTTPAuth https://github.com/miguelgrinberg/Flask-HTTPAuth?

**Comment by rycus86** [comment]
Good question! Let me investigate a bit and get back to you on this (hopefully later this week).

Until then, an alternative could be having a reverse proxy in front of the Flask app doing the basic auth on endpoints that require it, e.g. an Ngonx protecting the /metrics endooint for example.

**Comment by rycus86** [comment]
I've now added support for this in the linked commit, will be released shortly in version `0.18.0`. Thanks for reporting this!
See https://github.com/rycus86/prometheus_flask_exporter#securing-the-metrics-endpoint for example usage and https://github.com/rycus86/prometheus_flask_exporter/blob/master/examples/flask-httpauth/httpauth_example.py for a full example.

**Comment by riyadparvez** [comment]
Amazing! Thanks for responding so promptly.
