### ISSUE TITLE
Can I use @metrics.export_defaults()?

### ISSUE THREAD

**Issue by cristifalcas** [rycus86/prometheus_flask_exporter#84]
I want to set export_defaults to False, and use `@metrics.export_defaults()` decorator for specific endpoints.

But I'm getting this exception:
```
    @metrics.export_defaults()
TypeError: 'NoneType' object is not callable
```

Is this supported?

**Comment by rycus86** [comment]
Nope, that is a method of the metrics instance to set up those default metrics once.
What exactly do you want to achieve by adding it to specific endpoints? (by default you'd get it on all of them)
If you want the default everywhere except some endpoints, you can mark those with `@metrics.do_not_track()`

**Comment by cristifalcas** [comment]
I was trying to make the default to be without metrics and only add it to specific endpoints.

Thank you
