### ISSUE TITLE
Adding default_labels to process_cpu_seconds_total and process_resident_memory_bytes

### ISSUE THREAD

**Issue by dkaoster** [rycus86/prometheus_flask_exporter#85]
Thank you so much for this library, it's been extremely helpful.

I'm wondering if there's any way to also include the labels provided by `default_labels` to `process_cpu_seconds_total` and `process_resident_memory_bytes`?

I'm running prometheus flask exporter with `metrics = PrometheusMetrics(app, default_labels={'hostname': hostname})` and I'm seeing `hostname` show up as a label in all the  `flask_*` metrics, but not in any other ones. Is there another place to add labels to these metrics?

**Comment by rycus86** [comment]
Thanks a lot for the kind words, I'm glad you found it useful! 🙂

Looking at https://github.com/prometheus/client_python/blob/master/prometheus_client/process_collector.py#L51 it doesn't look like it accepts any label configuration parameters, only the prefix can be changed potentially.

**Comment by dkaoster** [comment]
Sounds good, I'll try another method - thanks for the help!
