### ISSUE TITLE
Connexion - Gathering metrics when /metrics is hit

### ISSUE THREAD

**Issue by dan-origami** [rycus86/prometheus_flask_exporter#86]
Loving this module so far, thanks for your work.

Not sure if I am doing something wrong, but I am using `ConnexionPrometheusMetrics`  and it works fine, but what I am struggling with is I would like to gather some metrics (say for example test a database connection) when /metrics is hit.

Adding an `@app.route('/metrics')` doesn't seem to work and it seems register_endpoint doesn't function properly with `ConnexionPrometheusMetrics`

As a simple case let's say I have a counter

```
import connexion
from connexion.resolver import RestyResolver
from flask_cors import CORS
from prometheus_flask_exporter import ConnexionPrometheusMetrics, Gauge, Counter, Summary
import time
import requests

# create the application instance
app = connexion.App(__name__, specification_dir="./")
CORS(app.app)
metrics = ConnexionPrometheusMetrics(app)

test_counter = Counter('test_counter', "it counts, or does it?")

# Some way of hijacking /metrics
def hijack_metrics():
  test_counter.inc()
  pass

```
Is this possible under this setup? test_counter appears on the /metrics output but I can't get it to inc when /metrics is called, if I chuck it under a different `app.route` or some other logic it works fine, but I need a way of backgrounding some calls that are not linked to an API endpoint to compute these metrics.

**Comment by rycus86** [comment]
> Loving this module so far, thanks for your work.

Thanks a lot! Glad you found it useful!

Not sure I completely understand what you're trying to achieve here, sorry.
Are you trying to do additional work when the `/metrics` endpoint is hit by Prometheus scraping?
Or are you having problems getting non-endpoint counters to correctly show their value on the metrics endpoint?

**Comment by dan-origami** [comment]
Basically this,

> Are you trying to do additional work when the `/metrics` endpoint is hit by Prometheus scraping?

Is it possible to trigger some functions/defs when /metrics is hit?

If i was adding my own routes via `@app.route('/some/route')` I could just have them there but not sure how to achieve this for /metrics

**Comment by rycus86** [comment]
Thanks for clarifying! I'm super interested in your use-case for this btw if you can share, what sorts of things do you want to hook in there?

One way I can see that you could try is preventing this library exposing the default `/metrics` endpoint, by passing `path=None` when you create the instance.
Then you should be able to create your own routing for your own metrics endpoint, which should do something like this library would here: https://github.com/rycus86/prometheus_flask_exporter/blob/master/prometheus_flask_exporter/__init__.py#L240
You should be able to add any custom logic in your own endpoint implementation then.

> I'm also playing catchup a bit with Connexion, so might just be doing something stupid

I have to say, Connexion is not something I'm super familiar with either, so I wouldn't be surprised if you found that this library is not doing something right. If you do find that, please let me know! 🙂

**Comment by rycus86** [comment]
Forgot to say, let me know how this works out for you please!
If it can't work like I suggested, perhaps we could add a hook function to run as part of that metrics method in this library, if you have a strong use-case for it that other could potentially benefit from too maybe?

**Comment by dan-origami** [comment]
Cheers for the responses, i'll have a play with some stuff today and see how it goes.

> Thanks for clarifying! I'm super interested in your use-case for this btw if you can share, what sorts of things do you want to hook in there?

Basically I would like to add some metrics about our service that aren't just flask stuff, mostly things around database stats (and other health/sanity based stuff). Unfortunately this service doesn't have just one class managing db connections, but hundreds of functions all doing their own db connections so I couldn't inject the metrics into a nice place to keep track of it. So it makes sense to roll all this up into just computing when /metrics is called and running a few small checks/data gathering operations.
I was able to do this with the raw prometheus_client library, but then I found your flask module which is way better for the detailed api stats.

I guess it's probably possible to add in some background function that runs every so often to collect these metrics if I can't do it on /metrics with Connexion

For reference just using `prometheus_client` it looked like (this was also a learning experience on writing prom metrics in Python so it's a little rough)

```python
from flask import render_template, redirect
from app import app as application
from werkzeug.middleware.dispatcher import DispatcherMiddleware
from werkzeug.wrappers import Request, Response
from prometheus_client import make_wsgi_app
from metrics import gather_metrics
from prometheus_client import multiprocess
from prometheus_client import generate_latest, CollectorRegistry, CONTENT_TYPE_LATEST

@application.route("/")
def home():
    """
    Redirect the root to the API documentation.

    :return:        API's Connexion/Swagger UI
    """
    return redirect("/ui")

@application.route("/metrics")
def metrics():
    gather_metrics()
    registry = CollectorRegistry()
    multiprocess.MultiProcessCollector(registry)
    data = generate_latest(registry)
    status = '200 OK'
    response_headers = [
        ('Content-type', CONTENT_TYPE_LATEST),
        ('Content-Length', str(len(data)))
    ]
    # start_response(status, response_headers)
    #return iter([data])
    #return make_wsgi_app()
    return Response(response=data, status=200, headers=response_headers)
```

```python
from prometheus_client import Summary, Gauge, Counter
import random
import time
import requests

# Create a metric to track time spent and requests made.
METRICS_CALL_COUNT=Counter("metrics_call_count", "count of calls to /metrics", multiprocess_mode='max')
NGINX_REQUESTS = Gauge("nginx_requests", "requests to nginx", multiprocess_mode='max')
NGINX_CONNECTIONS = Gauge('nginx_connections', 'connections to nginx', multiprocess_mode='max')

def metrics_count():
  METRICS_CALL_COUNT.inc()

def nginx_requests():
    r = requests.get('http://localhost:8081/status')
    splitted = r.text.split(" ")
    NGINX_REQUESTS.set(splitted[9])
    NGINX_CONNECTIONS.set(splitted[2])

def gather_metrics():
    nginx_requests()
    metrics_call_count()

```

**Comment by dan-origami** [comment]
Jumping back in, your idea works, nice one! No idea why it didn't occur to me to do what I had done with the regular prom_client stuff and implement it here as well.... but whatever.

Super clean and nice way of doing it, obviously i've chopped out loads of the extra stuff here like the `metrics_decorator` but i'll go back and add it in now i know it works. Thanks for the swift responses/insight.

```python

metrics = ConnexionPrometheusMetrics(app, path=None)

test_counter = Counter('test_counter', "it counts, or does it?")

@app.route('/metrics')
@metrics.do_not_track()
def metrics_page():
    """
    Register the metrics endpoint on the Flask application.
    :param path: the path of the endpoint
    :param app: the Flask application to register the endpoint on
        (by default it is the application registered with this class)
    """
    test_counter.inc()
    gather_metrics_functions()
    # import these here so they don't clash with our own multiprocess module
    from prometheus_client import multiprocess, CollectorRegistry
    if 'prometheus_multiproc_dir' in os.environ:
        registry = CollectorRegistry()
    if 'prometheus_multiproc_dir' in os.environ:
        multiprocess.MultiProcessCollector(registry)
    generate_latest, content_type = choose_encoder(request.headers.get("Accept"))
    headers = {'Content-Type': content_type}
    return generate_latest(registry), 200, headers
```

**Comment by rycus86** [comment]
I'm glad you got it working! 👍 
It's a clever way of doing it, if it works for you then it's definitely not horrendous. 🙂

The only thing I could think of is that this way you rely on the Prometheus scraper to trigger metrics collections, not sure if your app can tolerate that going away (due to network issues, etc), or changing scraping intervals.
If you're looking for an alternative, perhaps a `Timer` to collect these metrics on a schedule independent from scraping might be an option, but again if this works for you, then it's totally fine.

Are you OK to close this issue, or is there anything else we need to discuss here?
