### ISSUE TITLE
Metrics are not exposed with the UWsgiPrometheusMetrics

### ISSUE THREAD

**Issue by bjorxi** [rycus86/prometheus_flask_exporter#87]
Hi. I've tried to setup flask exporter with uWSGI, but it doesn't work.
Here is how I do it
```python

import flask
from prometheus_flask_exporter.multiprocess import UWsgiPrometheusMetrics

app = flask.Flask(__name__)
PROM = UWsgiPrometheusMetrics(app, path="/metrics")
PROM.start_http_server(9100)
```

And when I make a call
```bash
curl http://localhost:9100/metrics
```
curl hangs out without response.

I looked at the code and found that here: https://github.com/rycus86/prometheus_flask_exporter/blob/master/prometheus_flask_exporter/multiprocess.py#L59

path is None, which led me to  this line https://github.com/rycus86/prometheus_flask_exporter/blob/master/prometheus_flask_exporter/__init__.py#L230

The `register_endpoint` method was not executed.

After I removed the `path` param from here:
https://github.com/rycus86/prometheus_flask_exporter/blob/master/prometheus_flask_exporter/multiprocess.py#L59
the `register_endpoint` method was executed and I could scrape metrics.

Is it a but or I did something wrong ?

**Comment by rycus86** [comment]
Hello @bjorxi 
That code path should not set the path there if I remember correctly, I think the later start will take care of it.
Have you had a look at https://github.com/rycus86/prometheus_flask_exporter/tree/master/examples/uwsgi ?
That is a working example, where the Python code is more or less the same as yours, perhaps check my Dockerfile and let me know what you do differently with the uwsgi invocation?
It could be that my code doesn't work for how you start it perhaps, then we could work out a fix if that's the case.

**Comment by bjorxi** [comment]
Hi. Thanks for the reply.
The example really worked find. Have not figure out yet why in my case it does not work.

**Comment by bjorxi** [comment]
Totally forgot that uWSGI by default blocks threads, and the metrics server runs in a Python thread. That was the problem. uWSGI has to be ran with the `--enable-threads` or `--threads n` flags.

**Comment by rycus86** [comment]
Good find! 🙂
