### ISSUE TITLE
disable Histogram, but leave http_request_total counter?

### ISSUE THREAD

**Issue by Anamura** [rycus86/prometheus_flask_exporter#95]
Hello is it possible to disable Histogram, but leave http_request_total counter?

thank you

**Comment by rycus86** [comment]
I think there's no explicit support for this at the moment, but could be added if you have a use case. As a workaround, you could avoid the default metrics registration, then register your own default using `metrics.register_default`, but again better support for this can be added if that's helpful.

**Comment by Anamura** [comment]
yes, works great! thank you.

ps it was just some performance issues when app is handle file download,
1000- different urls and no need to analyze each.
